# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lender_name', models.CharField(max_length=255)),
                ('repayment_day', models.DateField()),
                ('repayment_num', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('repayment_interval', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='delayornot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='expensecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='fluctationexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='fluctationincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_or_ind', models.IntegerField()),
                ('thumbnail_path', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=75)),
                ('post_num', models.CharField(max_length=255)),
                ('prefecture', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='incomecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='jobtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='membertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='paidstatuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='sexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='staticexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category_staticexpense', to='analyzeViewer.incomecategory')),
                ('paidornot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidornot_staticexpense', to='analyzeViewer.paidstatuse')),
            ],
        ),
        migrations.CreateModel(
            name='staticexpensedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('paid_date', models.DateTimeField()),
                ('delay_amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('delay_or_not', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_or_not_staticexpensedetail', to='analyzeViewer.delayornot')),
                ('paidornot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidornot_staticexpensedetail', to='analyzeViewer.paidstatuse')),
            ],
        ),
        migrations.CreateModel(
            name='staticincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category_staticincome', to='analyzeViewer.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='staticincomedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('paid_date', models.DateTimeField()),
                ('delay_amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('delay_or_not', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_or_not_staticincomedetail', to='analyzeViewer.delayornot')),
                ('paidornot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidornot_staticincomedetail', to='analyzeViewer.paidstatuse')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name_ruby', models.CharField(max_length=255)),
                ('last_name_ruby', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=75)),
                ('thumbnail_path', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='analyzeViewer.groups')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sex_id', to='analyzeViewer.sexs')),
            ],
        ),
        migrations.AddField(
            model_name='staticincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_staticincome', to='analyzeViewer.users'),
        ),
        migrations.AddField(
            model_name='staticexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_4', to='analyzeViewer.users'),
        ),
        migrations.AddField(
            model_name='groups',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='analyzeViewer.jobtypes'),
        ),
        migrations.AddField(
            model_name='groups',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_type', to='analyzeViewer.membertype'),
        ),
        migrations.AddField(
            model_name='fluctationincome',
            name='income_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category_fluctationincome', to='analyzeViewer.incomecategory'),
        ),
        migrations.AddField(
            model_name='fluctationincome',
            name='paidornot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidornot_fluctationincome', to='analyzeViewer.paidstatuse'),
        ),
        migrations.AddField(
            model_name='fluctationincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fluctationincome', to='analyzeViewer.users'),
        ),
        migrations.AddField(
            model_name='fluctationexpense',
            name='income_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category_fluctationexpense', to='analyzeViewer.incomecategory'),
        ),
        migrations.AddField(
            model_name='fluctationexpense',
            name='paidornot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidornot_fluctationexpense', to='analyzeViewer.paidstatuse'),
        ),
        migrations.AddField(
            model_name='fluctationexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_3', to='analyzeViewer.users'),
        ),
        migrations.AddField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_debt', to='analyzeViewer.users'),
        ),
    ]
